development:
  dialect: postgres
  datasource: user=icidasset dbname=keymaps_development sslmode=disable
  dir: db/migrations
  table: migrations

production:
  dialect: postgres
  datasource: HEROKU
  dir: db/migrations
  table: migrations
